### ISSUE TITLE
generate and reload camera parameter matrix

### ISSUE THREAD

**Issue by jacknlliu** [Lizmango/CV#7]
We follow the `YAML` configuration file format from [ros-drivers/video_stream_opencv](https://github.com/ros-drivers/video_stream_opencv/blob/master/config/test_calibration.yaml).

The format of the file `camera_calibration.yaml`:
```yaml
image_width: 1280
image_height: 960
camera_name: "0800461000822014"
camera_matrix:
  rows: 3
  cols: 3
  data: [2302.59, 0, 610.756, 0, 2309.46, 506.539, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.225495, -0.363048, -0.000477994, -0.000132753, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [2302.59, 0, 610.756, 0, 0, 2309.46, 506.539, 0, 0, 0, 1, 0]
```
**NOTE**: The value of parameter `distortion_model` is fixed as  `plumb_bob`. 

**TODO**:
-  [ ] generate the `.yaml` file after camera calibration, the `camera_matrix` parameters is what we concerned. (Here we use original python write file method to do output, not use the PyYaml module which cannot output the list as the inline mode. )
- [x] reload the `.yaml` file, print all the parameters and use the parameters of the camera to test.(use PyYaml module to load the calibration file.)

## Reference
- [PyYAML](https://pyyaml.org/wiki/PyYAMLDocumentation)
- [yaml example](http://yaml.readthedocs.io/en/latest/example.html)

**Comment by jacknlliu** [comment]
An example:
```py
import yaml

data = dict(
    A = 'a',
    B = dict(
        C = 'c',
        D = 'd',
        E = 'e',
    )
)

with open('data.yml', 'w') as outfile:
    yaml.dump(data, outfile, default_flow_style=False)
```
output of file
```
A: a
B:
  C: c
  D: d
  E: e
```



## Reference
- [How can I write data in YAML format in a file?](https://stackoverflow.com/questions/12470665/how-can-i-write-data-in-yaml-format-in-a-file)
